import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Common/Navbar";
import Footer from "./Component/Common/Footer";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "./Context/UserAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-orange-50`}
      >
        <AuthProvider>
          <ToastContainer
        position="top-right"
        autoClose={3000}
        pauseOnHover
        theme="light"
      />
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
